spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    username: sa
    password: ''
    url: jdbc:h2:file:./studentsdb
    #url: jdbc:h2:mem:users
    driverClassName: org.h2.Driver
    data: classpath:V1.1__data.sql
    continue-on-error: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update